spring:
  sql:
    init:
      mode: always
  main:
    banner-mode: console
  application:
    name: '@project.name@'
  jpa:
    database: postgresql
    show-sql: true
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        default_schema: "OAUTH"
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    hibernate:
      ddl-auto: none
  #    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/postgres
    #    username: postgres
    #    password: admin
    url: jdbc:postgresql://181.215.134.40:5432/orion
    username: postgres
    password: Orionsolution@2024
  banner:
    charset: UTF-8
server:
  port: 8081
  servlet:
    context-path: /oauth
    encoding:
      charset: '@project.build.sourceEncoding@'